"""add_rollypay_gateway

Revision ID: 419082e75b92
Revises: a9610b7b0f88
Create Date: 2026-05-21 17:50:52.575738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419082e75b92'
down_revision: Union[str, Sequence[str], None] = 'a9610b7b0f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # Alter the enum type in PostgreSQL
        # Check if ROLLYPAY already exists in paymentgateway enum to prevent DuplicateObjectError on retries
        check_query = sa.text(
            "SELECT 1 FROM pg_type t "
            "JOIN pg_enum e ON t.oid = e.enumtypid "
            "WHERE t.typname = 'paymentgateway' AND e.enumlabel = 'ROLLYPAY'"
        )
        exists = bind.execute(check_query).scalar()
        if not exists:
            with op.get_context().autocommit_block():
                op.execute("ALTER TYPE paymentgateway ADD VALUE 'ROLLYPAY'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
