"""add_auto_renew_to_subscriptions

Revision ID: 894b6a0eb210
Revises: 8795c1c27c28
Create Date: 2026-05-22 03:14:42.201420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894b6a0eb210'
down_revision: Union[str, Sequence[str], None] = '8795c1c27c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('auto_renew', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'auto_renew')
    # ### end Alembic commands ###
